# GLOBAL CONSTANTS 
    # game chars
UP_INDC_CHAR = '^'
DOWN_INDC_CHAR = 'V'
CORRECT_INDC_CHAR = '*'
INCORRECT_INDC_CHAR = 'X'
SEMI_INDC_CHAR = '!'
UNIDENTIFIED_LETTER_CHAR = '_'
    # table display chars
VERTICAL_SEPERATOR_CHAR = '='
HORIZONTAL_SEPERATOR_CHAR = '|'
CORNER_TABLE_CHAR = '+'
WHITESPACE_FILL_CHAR = ' '
    # logical constants
MAX_LINE_LENGTH = 140
HINT_ONE_GUESS_AMOUNT = 3
HINT_TWO_GUESS_AMOUNT = 7
HINT_THREE_GUESS_AMOUNT = 11